language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
   # Deal with all of the DZIL dependencies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil -Ilib authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
   # There seems a missing build-dependency on Pod::Coverage::TrustPod somewhere
   - cpanm --quiet --notest Pod::Coverage::TrustPod
   - dzil -Ilib listdeps | grep -vP '[^\w:]' | cpanm --verbose
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

script:
   - dzil -Ilib smoke --release --author
